### ISSUE TITLE
RNIap.flushFailedPurchasesCachedAsPendingAndroid is not a function

### ISSUE THREAD

**Issue by bcbcbcbcbcl** [dooboolab/react-native-iap#1140]
### Version of react-native-iap
4.5.4

### Version of react-native
0.60.3

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
Consume all 'ghost' purchases (that is, pending payment that already failed but is still marked as pending in Play Store cache) with RNIap.flushFailedPurchasesCachedAsPendingAndroid()

### Actual behavior
Got the error RNIap.flushFailedPurchasesCachedAsPendingAndroid is not a function

### Tested environment (Emulator? Real Device?)
Real Device

### Steps to reproduce the behavior
```
import * as RNIap from 'react-native-iap';

async componentDidMount() {
    try {
      const result = await RNIap.initConnection();
      await RNIap.flushFailedPurchasesCachedAsPendingAndroid();
      console.log('result', result);
    } catch (err) {
      console.warn(err.code, err.message);
    }
}
```

**Comment by AmauryLiet** [comment]
Hey @bcbcbcbcbcl, thanks for the issue!
I'm unable to reproduce the issue on my side unfortunately. Just to be sure, did you double check that you rebuilt the app after upgrading to v4.5.4?

**Comment by bcbcbcbcbcl** [comment]
@AmauryLiet Thanks for your reply! Yes, and the error disappeared today. LOL

**Comment by bcbcbcbcbcl** [comment]
@AmauryLiet Today I am getting this errors in debug mode & release mode respectively. The app crash in release mode. Do you have any idea what is going wrong here?

<img src="https://user-images.githubusercontent.com/39854319/95760838-13d60c00-0cde-11eb-8eda-7d75fa98af01.jpg" width="300"><img src="https://user-images.githubusercontent.com/39854319/95676309-c11e2680-0bef-11eb-9c13-96569f833809.jpg" width="300">

**Comment by AmauryLiet** [comment]
@bcbcbcbcbcl I see! this issue has been fixed in 4.6.1 ;)

**Comment by bcbcbcbcbcl** [comment]
@AmauryLiet Thank you so much for the information, really appreciate it! Updated to version 4.6.3 fixed the issue.

**Comment by phillmill** [comment]
Getting this issue after upgrading from 4.4.0 -> 5.2.14
