### ISSUE TITLE
E_IAP_NOT_AVAIBLE can't init RNIap after 3.0.0-rc.5 update

### ISSUE THREAD

**Issue by FallenDestiny** [dooboolab/react-native-iap#522]
### Version of react-native-iap
3.0.0-rc.5
### Version of react-native
0.59.8
### Platforms you faced the error (IOS or Android or both?)
iOS and ANDROID
### Expected behavior
Get products
### Actual behavior
Get error at E_IAP_NOT_AVAIBLE
### Tested environment (Emulator? Real Device?)
Real Device
### Steps to reproduce the behavior
After updating to 3.0.0-rc.5 from 3.0.0-rc.1, get error on simple init of RNIap. To mention that it worked before update , i just updated for Error Purchase handling , but now it don't work. 

![IMG_0373](https://user-images.githubusercontent.com/43267774/59498295-cfdeb700-8e9d-11e9-8eac-f61fbe45a65b.png)

```
const itemSubs = Platform.select({
    ios: [
      Keys.productIDIOS
    ],
    android: [
      Keys.productIDDroid,
    ],
  });
       const result = await RNIap.initConnection();
    
        const products = await RNIap.getSubscriptions(itemSubs);
        this.setState({ products });
    
        const awaible = await RNIap.getAvailablePurchases()
        console.log('products avaible : ', awaible);
```

Thanks!

**Comment by FallenDestiny** [comment]
Update: Found resolve for iOS. After update In-App Purchase was turned off. Turning on resolved the problem.
On Android found this errors: 

```
error: cannot find symbol
            } catch (ObjectAlreadyConsumedException oce) {
                     ^
  symbol: class ObjectAlreadyConsumedException

```

**Comment by FallenDestiny** [comment]
Update 2: Found resolve for Android. Insert `import com.facebook.react.bridge.ObjectAlreadyConsumedException;` in _RNIap.java_ in Android project. After that just build and run on device.

**Comment by hyochan** [comment]
@FallenDestiny Thanks for the reported fixed in `3.0.0-rc.6`
