### ISSUE TITLE
RNIap.getProducts is not a function

### ISSUE THREAD

**Issue by MariusCatanoiu** [dooboolab/react-native-iap#1811]
**Description**

I made an upgrade from v8.0.9 to v.8.6.3 and I get this errors:

`RNIap.getProducts is not a function. (In 'RNIap.getProducts(ids)','RNIap.getProducts' is undefined)`
on iOS simulator and physical device

`undefined  is not a function`
on Android emulator and physical device

**Environment:**

- react-native-iap: 8.6.3
- react-native:  0.69.3

**Comment by andresesfm** [comment]
Hello @MariusCatanoiu The method is still there: https://github.com/dooboolab/react-native-iap/blob/main/src/iap.ts#L145 and it's being exported. Are you using flow by any change?

**Comment by yanush** [comment]
I have a similar issue after upgrading from 8.5.1 to 8.6.3
I get "undefined is not a function" when calling RNIap.initConnection()
When looking in the source of the library I can see the function does exist

**Comment by jeremybarbet** [comment]
That must be coming on how the library and methods are now exported: `import * as RNIap`. I changed quite a lot of stuff at the same time and didn't think to try the star import.

Best guess would be to move from `import * as RNIap` to `import * as RNIap`.

If that still doesn't work, you could check if the method/type you are looking for is part of the destructured import `import { the_method } from 'react-native-iap';`

Sorry about that, it's not ideal, I have been doing a lot of changes and definitely broke some stuff along the way. 

cc/ @andresesfm Maybe we should release under a pre/alpha version while we are working on theses changes. Not sure what you think. We could unpublish on npm up to 8.5.2, remove the releases on github as well for now, and release under a new version later (f.x. 8.7.0) with a more descriptive breaking change changelog. I will definitely break/change more stuff in later PR regarding imports/types (cf/ #1797).

**Comment by MariusCatanoiu** [comment]
`Change "import * as RNIap from 'react-native-iap';" to "import RNIap from 'react-native-iap';"`
this fixed the issue. Thanks!

**Comment by MariusCatanoiu** [comment]
Now, the issue is that I get app crash on android on RNIap.requestPurchase

`2022-08-06 17:44:14.706 24529-24718/? E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter sku
        at com.dooboolab.RNIap.RNIapModule.buyItemByType`
        
No issue on iOS

**Comment by jeremybarbet** [comment]
That's not related tot he initial error.

How are you calling either `requestPurchase` or `requestSubscription`? it sounds like the `sku` parameter to one of the two function is null and should be instead a string.

Methods signature changed from `requestPurchase/requestSubscription(sku)` to `requestPurchase/requestSubscription({ sku })`
