### ISSUE TITLE
cannot find symbol       DoobooUtils.getInstance().rejectPromiseWithBillingError(promise, billingResult.getResponseCode());

### ISSUE THREAD

**Issue by LzazSports** [dooboolab/react-native-iap#764]
### Steps to reproduce the behavior

After updating to 4.0 getting the error:

cannot find symbol
      DoobooUtils.getInstance().rejectPromiseWithBillingError(promise, billingResult.getResponseCode());

**Comment by ZodiacGemini** [comment]
I have the same issue, solved it temporarily by changing:
`DoobooUtils.getInstance().rejectPromiseWithBillingError(promise, billingResult.getResponseCode());`
to
`DoobooUtils.getInstance().rejectPromisesWithBillingError(PROMISE_BUY_ITEM, billingResult.getResponseCode());`

in node_modules. Don't know if this is a valid fix, so maybe someone should look into the expected behavior!

**Comment by LukePenkava** [comment]
React Native version: 0.61.2
react-native-iap version: 4.0.0
Platform: Android, Android studio 3.4.2

Same error here, here is a bit more info

```
> Task :react-native-iap:compileDebugJavaWithJavac FAILED
/Users/home/Desktop/APLIKACE/test/node_modules/react-native-iap/android/src/main/java/com/dooboolab/RNIap/RNIapModule.java:506: error: cannot find symbol
      DoobooUtils.getInstance().rejectPromiseWithBillingError(promise, billingResult.getResponseCode());
                                                              ^
  symbol:   variable promise
  location: class RNIapModule
Note: /Users/home/Desktop/APLIKACE/test/node_modules/react-native-iap/android/src/main/java/com/dooboolab/RNIap/RNIapModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-iap:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

BUILD FAILED in 36s
252 actionable tasks: 225 executed, 27 up-to-date
```

**Comment by hyochan** [comment]
Please try `4.0.1`.
