### ISSUE TITLE
getSubscriptions not working on ios 13

### ISSUE THREAD

**Issue by ivpusic** [dooboolab/react-native-iap#787]
### Version of react-native-iap
4.0.4

### Version of react-native
0.61.2

### Platforms you faced the error (IOS or Android or both?)
ios

### Expected behavior
It fetches list of subscriptions

### Actual behavior
infinitely loading getSubscriptions

### Tested environment (Emulator? Real Device?)
real device

we also noticed that restarting of the mobile phone helps...after that we can load subscriptions, but next time we try it, it does not work anymore

**Comment by redvulps** [comment]
Having this issue too, data is loaded on simulator, but on the real device (iPhone 7, iOS 13.1.2).

I can confirm that restarting the device make the subscriptions show up again. But, after first loading of the results, doesn't show up again and I have to restart the device to get the data loaded.

I also found that this also affects **RNIap.getProducts**.

Test were made with version 4.0.4 of react-native-iap.

Is there any logs or something I could provide to help with this issue?

**Comment by ivpusic** [comment]
after furher investigation, looks like it is only happening when using sandbox account for testing

**Comment by hyochan** [comment]
> sandbox

Looks like this is an issue on `apple`'s side.

**Comment by matamicen** [comment]
+1

**Comment by tarasfo** [comment]
Discussed on call

**Comment by alexpchin** [comment]
On iOS 13 I'm also finding that the `getSubscriptions` does not resolve unless you restart the phone.

**Comment by alexpchin** [comment]
Does anyone have any thoughts on this?

**Comment by alexpchin** [comment]
It seems to me that RNIamIos.getItems(skus) does not resolve. This is the `SKProductsRequest`.

I'm on XCode Version 11.2.1 (11B500) and iOS 13.2.3.

- https://stackoverflow.com/questions/57633695/ios13-beta-5-does-skproductsrequest-supposed-to-work-on-simulator
- https://www.reddit.com/r/iOSProgramming/comments/d6m20l/skproductsrequest_returns_0_products_during_app/
- https://forums.developer.apple.com/thread/121208

```js
export var getSubscriptions = function (skus) {
    return Platform.select({
        ios: function () { return __awaiter(void 0, void 0, void 0, function () {
            return __generator(this, function (_a) {
                checkNativeiOSAvailable();
                console.log('I get here... ', RNIapIos.getItems(skus), skus)
                return [2 /*return*/, RNIapIos.getItems(skus).then(function (items) {
                    console.log('I do not get here...', items)
                        return items.filter(function (item) { return skus.includes(item.productId); });
                    }).catch(e => console.log('No error here...', e))];
            });
        }); },
        android: function () { return __awaiter(void 0, void 0, void 0, function () {
            return __generator(this, function (_a) {
                checkNativeAndroidAvailable();
                return [2 /*return*/, RNIapModule.getItemsByType(ANDROID_ITEM_TYPE_SUBSCRIPTION, skus)];
            });
        }); },
    })();
};
```

**Comment by bscheideldyrt** [comment]
@alexpchin I'm seeing the same thing.  I end up with this on DEV:

```
YellowBox.js:71 Error: Error decoding object
    at Object.fn [as getItems] (NativeModules.js:99)
    at index.js:174
    at step (index.js:32)
    at Object.next (index.js:13)
    at index.js:7
    at tryCallTwo (core.js:45)
    at doResolve (core.js:200)
    at new Promise (core.js:66)
    at __awaiter (index.js:3)
    at ios (index.js:170) undefined "error"
```

Live it seems to be working for most people, though we are seeing various failures like `Apple Store not available` which I'm trying to figure out if they are related or not.

**Comment by magickasoft** [comment]
`
Error: Error decoding object
    at Object.fn [as getItems] (NativeModules.js:99)
    at index.js:181
    at step (index.js:32)
    at Object.next (index.js:13)
    at index.js:7
    at tryCallTwo (core.js:45)
    at doResolve (core.js:200)
    at new Promise (core.js:66)
    at __awaiter (index.js:3)
    at ios (index.js:178)
`
simulator iPad Pro (12.9-inch) - 13.3 not working,
but it works on simulator iPad Pro (12.9-inch) - 12.2

have ideas how to fix the issue ?

**Comment by jackcb123** [comment]
Hello!

Came across this issue as well. Suddenly, getSubscriptions wasn't resolving (same with getProducts when I tried it) and I got messages like 'Invalid Status Code' on my Testflight builds (and even on simulator as well). This all happened recently and prior (a week or two ago) it was working no problem. And our production build which was on an older version of react-native-iap was working fine. My team tried various things like signing out of sandbox accounts on phones, restarting the phone, deleting the apps. Some times these things worked, and others not. We weren't able to completely reproduce the situations when it worked and when it didn't. 

After looking around the web for answers it seemed that this is just a problem with Testflight builds, so with the encouragement of a certain bearded developer who had no idea what we were all yapping about we said screw it and released it #beardconfidence. On production it seems to work fine. I'll report back if we continue to see issues, but as far as I can tell (annoying as the issue is) this really is just a sandbox issue and production is unaffected. 

Hope it gets fixed soon though so we can do better, more consistent testing :)

**Comment by roonskipp** [comment]
Hitting this issue in 2023

**Comment by TahseenSust** [comment]
Check if the subscription is available in your current location. I Faced a similar issue and after turning on the VPN I successfully fetched all of my subscriptions.

**Comment by Saad962404** [comment]
> Check if the subscription is available in your current location. I Faced a similar issue and after turning on the VPN I successfully fetched all of my subscriptions.

Where I can find the list of avaiable region?
