### ISSUE TITLE
Error on link Xcode with version 2.4.9

### ISSUE THREAD

**Issue by dpyeates** [dooboolab/react-native-iap#457]
### Version of react-native-iap
2.4.9
### Version of react-native
0.59.3
### Platforms you faced the error (IOS or Android or both?)
ios
### Expected behavior
links ok
### Actual behavior
link fails
### Steps to reproduce the behavior
The following error is given on link:

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_IAPPromotionObserver", referenced from:
      objc-class-ref in libRNIap.a(RNIapIos.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by hyochan** [comment]
Could you confirm this works fine in `2.4.8` or lower version? This may not be our problem.

**Comment by dpyeates** [comment]
Full unlink and uninstall and then install of 2.4.8 - OK
Then full unlink and uninstall and install of 2.4.9 - OK

My bad - must of been a funny with the link/build.

Thanks for the library! :-)
