### ISSUE TITLE
[iOS] Unable to Archive: Undefined symbols for architecture arm64: "_OBJC_CLASS_$_IAPPromotionObserver"

### ISSUE THREAD

**Issue by mvanroon** [dooboolab/react-native-iap#417]
### Version of react-native-iap
2.4.1

### Version of react-native
0.58.6

### Platforms you faced the error (IOS or Android or both?)
iOS

### Expected behavior
App can be Archived.

### Actual behavior
I am able to Build, but not Archive my app.

### Tested environment (Emulator? Real Device?)
N/A

### Steps to reproduce the behavior
Try to build an app using rn 0.58.6 and rn-iap 2.4.1

I am unable to run my app after upgrading react-native-iap to 2.4.1:

```Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_IAPPromotionObserver", referenced from:
      objc-class-ref in libRNIap.a(RNIapIos.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

- I'm not sure of this is a duplicate of #395.
- Downgrading to an earlier version of react-native-iap fixes the problem.
- `$(SRCROOT)/../node_modules/react-native-iap/ios [recursive]` is in my `header search paths`.

**Comment by hyochan** [comment]
Could you also try #14?

**Comment by mvanroon** [comment]
Thanks @hyochan but I installed it manually - not via pods.

**Comment by hyochan** [comment]
This isn't reproducible in my environment. However, I found someone fixing the problem themselves by `linking` and `unlinking` again.

**Comment by mvanroon** [comment]
I tried relinking, but unfortunately this doesn't work. I've downgraded to 2.3 for now

**Comment by hyochan** [comment]
Could you also look at [this one](https://github.com/facebook/react-native/issues/11900#issuecomment-275953266)?

Also, you can try deleting `ios/build` and try again.

Actually, this problem doesn't seem to belong to us though.

Hope you can come back after trying above. Thanks!

**Comment by mvanroon** [comment]
Thank you for taking the time to help me.

I've tried removing the `ios/build` folder, but it didn't work. I am able to Build (develop), but not Archive (release) it.

**Comment by hyochan** [comment]
@mvanroon Thanks for trying out. This is really helpful👍. Might better put this in the readme if more people coming for the same problem. I'll close this for now.
